-- Create Database

CREATE DATABASE IF NOT EXISTS SFO_FLIGHTS;
USE DATABASE SFO_FLIGHTS;


-- Dimension: Date

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY DATE PRIMARY KEY,
    DAY INT,
    MONTH INT,
    YEAR INT,
    DAY_OF_WEEK STRING,
    WEEK_OF_YEAR INT,
    IS_HOLIDAY BOOLEAN DEFAULT FALSE
);


-- Dimension: Airline
CREATE OR REPLACE TABLE DIM_AIRLINE (
    AIRLINE_KEY STRING PRIMARY KEY,      -- Surrogate key, e.g., AIRLINE_CODE
    AIRLINE_CODE STRING,
    AIRLINE_NAME STRING,
    AIRLINE_DOT STRING
);


CREATE OR REPLACE TABLE DIM_AIRPORT (
    AIRPORT_KEY STRING PRIMARY KEY,      -- Use airport code as surrogate key
    CITY STRING,
    STATE STRING,
    COUNTRY STRING DEFAULT 'USA'
);



CREATE OR REPLACE TABLE FACT_FLIGHT (
    FLIGHT_KEY STRING PRIMARY KEY,       -- Surrogate key (e.g., concat of date+flight_number+origin+dest)
    
    -- Foreign Keys
    DATE_KEY DATE REFERENCES DIM_DATE(DATE_KEY),
    AIRLINE_KEY STRING REFERENCES DIM_AIRLINE(AIRLINE_KEY),
    ORIGIN_AIRPORT_KEY STRING REFERENCES DIM_AIRPORT(AIRPORT_KEY),
    DEST_AIRPORT_KEY STRING REFERENCES DIM_AIRPORT(AIRPORT_KEY),
    
    -- Degenerate Dimensions
    FLIGHT_NUMBER STRING,
    
    -- Measures / Metrics
    CRS_DEP_TIME STRING,
    DEP_TIME STRING,
    DEP_DELAY INT,
    TAXI_OUT INT,
    WHEELS_OFF STRING,
    WHEELS_ON STRING,
    TAXI_IN INT,
    CRS_ARR_TIME STRING,
    ARR_TIME STRING,
    ARR_DELAY INT,
    CANCELLED BOOLEAN,
    CANCELLATION_CODE STRING,
    DIVERTED BOOLEAN,
    CRS_ELAPSED_TIME INT,
    ELAPSED_TIME INT,
    AIR_TIME INT,
    DISTANCE FLOAT,
    DELAY_DUE_CARRIER INT DEFAULT 0,
    DELAY_DUE_WEATHER INT DEFAULT 0,
    DELAY_DUE_NAS INT DEFAULT 0,
    DELAY_DUE_SECURITY INT DEFAULT 0,
    DELAY_DUE_LATE_AIRCRAFT INT DEFAULT 0
);